SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[viewSecondaryImpTypesPivoted]
as
select 
        MTPID,
        [New Facility-Road] = ISNULL([New Facility-Road], 0),
        [Single Intersect] = ISNULL([Single Intersect], 0),
        [Multiple Intersects] = ISNULL([Multiple Intersects], 0),
        [Major Interchange-GP] = ISNULL([Major Interchange-GP], 0),
        [Relocation-Road] = ISNULL([Relocation-Road], 0),
        [Major Interchange-HOV] = ISNULL([Major Interchange-HOV], 0),
        [Minor Interchange-GP] = ISNULL([Minor Interchange-GP], 0),
        [Minor Interchange-HOV] = ISNULL([Minor Interchange-HOV], 0),
        [Grade Separation] = ISNULL([Grade Separation], 0),
        [Direct Access - HOV or Tolled Lane] = ISNULL([Direct Access - HOV or Tolled Lane], 0),
        [Implements HOT, tolling policy] = ISNULL([Implements HOT, tolling policy], 0),
        [Improvement-Road] = ISNULL([Improvement-Road], 0),
        [Other-Road] = ISNULL([Other-Road], 0),
        [New/Widen Bridge] = ISNULL([New/Widen Bridge], 0),
        [Bridge Replace] = ISNULL([Bridge Replace], 0),
        [Bridge Rehab] = ISNULL([Bridge Rehab], 0),
        [Safety-Road] = ISNULL([Safety-Road], 0),
        [Vehicle Expansion] = ISNULL([Vehicle Expansion], 0),
        [P & R (new/expand spaces)] = ISNULL([P & R (new/expand spaces)], 0),
        [Transit Ctr (new/expand)] = ISNULL([Transit Ctr (new/expand)], 0),
        [Transit Service Expansion] = ISNULL([Transit Service Expansion], 0),
        [Major Widening-GP] = ISNULL([Major Widening-GP], 0),
        [Flyer Stop] = ISNULL([Flyer Stop], 0),
        [Transit Infrastructure/Expansion - Bus] = ISNULL([Transit Infrastructure/Expansion - Bus], 0),
        [Transit Infrastructure/Expansion - HCT] = ISNULL([Transit Infrastructure/Expansion - HCT], 0),
        [Transit Ctr (maint)] = ISNULL([Transit Ctr (maint)], 0),
        [Operations-Transit] = ISNULL([Operations-Transit], 0),
        [Other-Transit] = ISNULL([Other-Transit], 0),
        [Transit ITS] = ISNULL([Transit ITS], 0),
        [Signal Coordination] = ISNULL([Signal Coordination], 0),
        [Traffic Surveilance] = ISNULL([Traffic Surveilance], 0),
        [ITS - Other] = ISNULL([ITS - Other], 0),
        [Operations - System Management] = ISNULL([Operations - System Management], 0),
        [Lane Control] = ISNULL([Lane Control], 0),
        [Incident Detection] = ISNULL([Incident Detection], 0),
        [Incident Response] = ISNULL([Incident Response], 0),
        [Traveller Information - Other] = ISNULL([Traveller Information - Other], 0),
        [TDM] = ISNULL([TDM], 0),
        [Regional Trail (Sep.)] = ISNULL([Regional Trail (Sep.)], 0),
        [Local Trail] = ISNULL([Local Trail], 0),
        [Sidewalk] = ISNULL([Sidewalk], 0),
        [On-Road Bike/Ped Facilities] = ISNULL([On-Road Bike/Ped Facilities], 0),
        [Bike/Ped - supportive strategies] = ISNULL([Bike/Ped - supportive strategies], 0),
        [Other-Nonmotorized] = ISNULL([Other-Nonmotorized], 0),
        [Minor Widening] = ISNULL([Minor Widening], 0),
        [New/Reloc./Exp. Terminal] = ISNULL([New/Reloc./Exp. Terminal], 0),
        [New ferry route] = ISNULL([New ferry route], 0),
        [Service Exp-Ferry] = ISNULL([Service Exp-Ferry], 0),
        [Study/Planning Activity] = ISNULL([Study/Planning Activity], 0),
        [Other-Special] = ISNULL([Other-Special], 0),
        [Major Widening-HOV] = ISNULL([Major Widening-HOV], 0),
        [Lane Conversions] = ISNULL([Lane Conversions], 0),
        [Pres/Maint/Reconst] = ISNULL([Pres/Maint/Reconst], 0),
        [Transit Signal Priority] = ISNULL([Transit Signal Priority], 0),
        [Integrated Corridor Management] = ISNULL([Integrated Corridor Management], 0),
        [New/Relocated Transit Alignment] = ISNULL([New/Relocated Transit Alignment], 0)
from (
    SELECT pit.MTPID, i.ImpTypeName
    FROM tblProj_SecondaryImptype pit
        join tblImproveType i on pit.ImpTypeID = i.ImpTypeID
) as qry  
PIVOT (
    count(ImpTypeName)
    for ImpTypeName in (
        [New Facility-Road],
        [Single Intersect],
        [Multiple Intersects],
        [Major Interchange-GP],
        [Relocation-Road],
        [Major Interchange-HOV],
        [Minor Interchange-GP],
        [Minor Interchange-HOV],
        [Grade Separation],
        [Direct Access - HOV or Tolled Lane],
        [Implements HOT, tolling policy],
        [Improvement-Road],
        [Other-Road],
        [New/Widen Bridge],
        [Bridge Replace],
        [Bridge Rehab],
        [Safety-Road],
        [Vehicle Expansion],
        [P & R (new/expand spaces)],
        [Transit Ctr (new/expand)],
        [Transit Service Expansion],
        [Major Widening-GP],
        [Flyer Stop],
        [Transit Infrastructure/Expansion - Bus],
        [Transit Infrastructure/Expansion - HCT],
        [Transit Ctr (maint)],
        [Operations-Transit],
        [Other-Transit],
        [Transit ITS],
        [Signal Coordination],
        [Traffic Surveilance],
        [ITS - Other],
        [Operations - System Management],
        [Lane Control],
        [Incident Detection],
        [Incident Response],
        [Traveller Information - Other],
        [TDM],
        [Regional Trail (Sep.)],
        [Local Trail],
        [Sidewalk],
        [On-Road Bike/Ped Facilities],
        [Bike/Ped - supportive strategies],
        [Other-Nonmotorized],
        [Minor Widening],
        [New/Reloc./Exp. Terminal],
        [New ferry route],
        [Service Exp-Ferry],
        [Study/Planning Activity],
        [Other-Special],
        [Major Widening-HOV],
        [Lane Conversions],
        [Pres/Maint/Reconst],
        [Transit Signal Priority],
        [Integrated Corridor Management],
        [New/Relocated Transit Alignment]        
    )
    ) as PivotTable
GO
