CREATE TABLE [stg].[projects]
(
[id] [bigint] NULL,
[user_id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[created_at] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[updated_at] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[submitted_at] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accepted_at] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_project] [bit] NULL,
[modify_from_unprogrammed_to_constrained] [bit] NULL,
[modify_constrained_project_details] [bit] NULL,
[project_id] [float] NULL,
[sponsoring_agency_id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[title] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_first_name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_last_name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_email] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_phone] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mtp_status] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[planning_process] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[letters_of_concurrence] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[endpoint_a] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[endpoint_b] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[milepost_a] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[milepost_b] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[county_id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_cost] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[constant_dollar_year] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[funds_description] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primary_improvement_type_id] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[start_year] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[completion_year] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[functional_class] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[change_in_project_scope] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prioritization_a1a] [float] NULL,
[prioritization_a1b] [float] NULL,
[prioritization_a2a] [float] NULL,
[prioritization_a2b] [float] NULL,
[prioritization_a3] [float] NULL,
[prioritization_a4] [float] NULL,
[prioritization_a4_continued] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prioritization_f1] [float] NULL,
[prioritization_f2] [float] NULL,
[prioritization_f3] [float] NULL,
[prioritization_f4a] [float] NULL,
[prioritization_f4b] [float] NULL,
[prioritization_f5] [float] NULL,
[prioritization_f6] [float] NULL,
[prioritization_j1a] [float] NULL,
[prioritization_j1b] [float] NULL,
[prioritization_j2] [float] NULL,
[prioritization_j3] [float] NULL,
[prioritization_j4] [float] NULL,
[prioritization_m1] [float] NULL,
[prioritization_m2] [float] NULL,
[prioritization_m3] [float] NULL,
[prioritization_m4] [float] NULL,
[prioritization_m5] [float] NULL,
[prioritization_m6] [float] NULL,
[prioritization_m7] [float] NULL,
[prioritization_w1a] [float] NULL,
[prioritization_w1b] [float] NULL,
[prioritization_w1c] [float] NULL,
[prioritization_w1d] [float] NULL,
[prioritization_w2] [float] NULL,
[prioritization_w4a] [float] NULL,
[prioritization_w4b] [float] NULL,
[prioritization_s1a] [float] NULL,
[prioritization_s1b] [float] NULL,
[prioritization_s1c] [float] NULL,
[prioritization_s2] [float] NULL,
[prioritization_o1] [float] NULL,
[prioritization_o2a] [float] NULL,
[prioritization_o2b] [float] NULL,
[prioritization_o2c] [float] NULL,
[prioritization_o3a] [float] NULL,
[prioritization_o3b] [float] NULL,
[prioritization_o3c] [float] NULL,
[prioritization_c1a] [float] NULL,
[prioritization_c1b] [float] NULL,
[prioritization_c1c] [float] NULL,
[prioritization_c2a] [float] NULL,
[prioritization_c2b] [float] NULL,
[prioritization_c3] [float] NULL,
[prioritization_c4] [float] NULL,
[prioritization_c5] [float] NULL,
[prioritization_t1] [float] NULL,
[prioritization_t2] [float] NULL,
[prioritization_t3] [float] NULL,
[prioritization_t4] [float] NULL,
[change_sponsoring_agency] [bit] NULL,
[change_title] [bit] NULL,
[change_description] [bit] NULL,
[change_location_information] [bit] NULL,
[change_total_cost] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[change_constant_dollar_year] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[change_completion_year] [bit] NULL,
[change_functional_class] [bit] NULL,
[current_step] [bigint] NULL,
[funds_committed] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prepopulated] [bit] NULL,
[change_start_year] [bit] NULL,
[old_total_cost] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[old_constant_dollar_year] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prioritization_m3a] [float] NULL,
[prioritization_m3b] [float] NULL,
[prioritization_m7a] [float] NULL,
[prioritization_m7b] [float] NULL,
[contact_2_first_name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_2_last_name] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_2_email] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_2_phone] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modify_complete] [bit] NULL,
[prioritization_w3] [float] NULL,
[updated_cost_explanation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cosponsors] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
